name: cinema
description: A new Flutter cinema project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  flutter_bloc: ^8.0.0
  provider: ^6.0.5
  dio: ^5.1.1
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.8.0
  crypto: ^3.0.2
  equatable: ^2.0.0
  mask_text_input_formatter: ^2.4.0
  enum_to_string: ^2.0.1
  qr_flutter: ^4.0.0
  # logger
  lumberdash: ^3.0.0
  print_lumberdash: ^3.0.0

  intl: ^0.18.1

  configurable_expansion_tile_null_safety: ^3.1.1
  cupertino_icons: ^1.0.2
  youtube_player_flutter: ^8.1.2
  collection:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
